package com.My.Spring_Final_Project.Enum.booking;

public enum BookingItemType {
    EXTRA_BED,
    BREAKFAST,
    LUNCH,
    DINNER,
    LAUNDRY,
    SPA,
    AIRPORT_PICKUP,
    AIRPORT_DROPOFF,
    ROOM_DECORATION,
    LATE_CHECKOUT,
    EARLY_CHECKIN,
    MINI_BAR,
    GYM_ACCESS,
    SWIMMING_POOL_ACCESS,
    CITY_TOUR,
    BABYSITTING_SERVICE,
    EXTRA_TOWELS,
    EXTRA_TOILETRIES
}
